### ISSUE TITLE
SUBHOOK_OPTION_64BIT_OFFSET detours get clobbered

### ISSUE THREAD

**Issue by psychonic** [Zeex/subhook#16]
With SUBHOOK_OPTION_64BIT_OFFSET set, subhook_make_jmp64 correctly gets called, but then subhook_make_jmp32 gets called unconditionally, overwriting the 64-bit jmp.

https://github.com/Zeex/subhook/blob/d2a5756f49082d837b3119671ee2f59e794e3166/subhook_x86.c#L272

**Comment by Zeex** [comment]
Fixed, thanks!
