### ISSUE TITLE
subhook_make_jmp overwrites orignal code in trampoline

### ISSUE THREAD

**Issue by psychonic** [Zeex/subhook#17]
For the call to subhook_make_jump from subhook_make_trampoline, after the source bytes are copied in, the jmp bytes are copied over top of them instead of after them.

I was able to fix this by changing the first arg to `(void *)(trampoline_addr + orig_size)`
https://github.com/Zeex/subhook/blob/d2a5756f49082d837b3119671ee2f59e794e3166/subhook_x86.c#L330

(Only tested with 64-bit hooking).

**Comment by Zeex** [comment]
Fixed this, thanks :beers:
