### ISSUE TITLE
Linux x64 hook failed

### ISSUE THREAD

**Issue by Na2CO3ren** [Zeex/subhook#30]
If the distance between original code and the trampoline is bigger than 32 bytes, the hook will failed. That would be so nice if anyone could tell me how to fix it.

**Comment by Zeex** [comment]
It should be possible to achieve this with `SUBHOOK_OPTION_64BIT_OFFSET`, when that option is used subhook puts a fat jump into the target address

```c
subhook_t foo_hook_tr = subhook_new((void *)foo,
                                    (void *)foo_hooked,
                                    SUBHOOK_OPTION_64BIT_OFFSET);
```
