### ISSUE TITLE
CMake cache variables

### ISSUE THREAD

**Issue by ziggi** [Zeex/subhook#32]
After these changes: 69ed7f0b52f0893778aa236585727c1cbb3e7813 we need to add `CACHE INTERNAL ""` into all of our subhook parameters for working after **first** cmake calling (after second and future calls everything is ok):
```cmake
set (SUBHOOK_STATIC true CACHE INTERNAL "")
set (SUBHOOK_TESTS false CACHE INTERNAL "")
```
This is by design?

**Comment by Zeex** [comment]
No, this was not intentional. It should be fixed now I think.
