### ISSUE TITLE
Segfault in tests on FreeBSD

### ISSUE THREAD

**Issue by ararslan** [Zeex/subhook#36]
Subhook looks really cool! It would be awesome if it could support FreeBSD. I tried building and testing locally, and it builds fine (with the addition of a trivial `#if defined(__FreeBSD__)`), but it segfaults while running the tests. I'll look more into this later to see what I can find out.

If you're interested, once things are working on FreeBSD, you could add it to your CI using [Cirrus CI](https://cirrus-ci.org) or [sr.ht](https://builds.sr.ht/).

**Comment by Zeex** [comment]
Thanks, I'll try to reproduce this bug on a VM

**Comment by Zeex** [comment]
FreeBSD is now supported

**Comment by ararslan** [comment]
Awesome!
