### ISSUE TITLE
Hooking fopen on Linux

### ISSUE THREAD

**Issue by IllidanS4** [Zeex/subhook#38]
I was hoping to intercept calls to fopen done by the server, like crashdetect does, but it seems not to do what I hoped for. I was able to hook CreateFileA on Windows, but calls to fopen that originate from the server are not intercepted; only mine are. Does crashdetect do something special for the hook to work?

**Comment by Zeex** [comment]
I think it depends on where `fopen` points to at runtime, it could be a pointer to the imports table shared by the process and all libraries or it could point to some other place internal to the module. IIRC there are linker flags that change this behavior (I don't remember using any special flags in crashdetect, maybe cmake handles it).

**Comment by IllidanS4** [comment]
Disabling PIC does not seem to make a difference, unfortunately. Crashdetect loads the pointer via `mov     eax, ds:(fopen_ptr - 44000h)[ebx]`, my plugin via `mov     [esp+1Ch+var_1C], offset fopen`, but there's something strange; IDA doesn't show the contents of the import table for my plugin, while it does for crashdetect and the server binary.
