### ISSUE TITLE
subhook_disasm can't be "subclassed"

### ISSUE THREAD

**Issue by JohnSully** [Zeex/subhook#39]
I want to create a disassembler that first tries the default disassembler and only takes over if that fails. This way I can hardcode support for just a few extra opcodes without needing a heavy disassembler.  However it feels like it was especially designed to make this impossible.  A few things that would make this a lot easier:

- subhook_disasm should be exported.  Then I can reference it in my custom disassembler.
- subhook_disasm_handler should be initialized with subhook_disasm.  Then I could get the address of subhook_disasm this way as an alternative to exporting it.

**Comment by Zeex** [comment]
Thanks for the suggestion, `subhook_disasm()` is exported now
