### ISSUE TITLE
Subhook 0.2 crash with YSF

### ISSUE THREAD

**Issue by kurta999** [Zeex/subhook#6]
I added SAMPGDK into YSF, and seems that subhook 0.2 doesn't like it. With 0.1 everything fine.

I'm anyway hook amx_Register from YSF, I think this caused this crash.

[code]
[debug] #0 01e8250a in SubHook::Install () from plugins\YSF.dll
[debug] #1 01e8b3ee in InstallPreHooks () from plugins\YSF.dll
[debug] #2 01e8c4d5 in Load () from plugins\YSF.dll
[debug] #3 00469e5b in ?? () from samp-server.exe
[debug] #4 00469fac in ?? () from samp-server.exe
[debug] #5 0018fd24 in ?? ()
[debug] #6 4ae32468 in ?? () from samp-server.exe
[debug] #7 6805eb00 in ?? () from samp-server.exe
[debug] #8 004ae330 in ?? () from samp-server.exe
[debug] #9 01d62fe8 in ?? ()
[debug] #10 64656c69 in ?? () from samp-server.exe
[/code]

**Comment by Zeex** [comment]
Did it work?

**Comment by kurta999** [comment]
Now yes, i try everything but now i can't reproduce that crash again.
