### ISSUE TITLE
Linker compilation errors

### ISSUE THREAD

**Issue by Hyjarion** [Zeex/subhook#67]
1>subhook.obj : warning LNK4006: subhook_new already defined in subhook_x86.obj; second definition ignored
1>subhook.obj : warning LNK4006: subhook_free already defined in subhook_x86.obj; second definition ignored
1>subhook.obj : warning LNK4006: subhook_install already defined in subhook_x86.obj; second definition ignored
1>subhook.obj : warning LNK4006: subhook_remove already defined in subhook_x86.obj; second definition ignored
1>subhook.obj : warning LNK4006: subhook_read_dst already defined in subhook_x86.obj; second definition ignored
1>subhook.obj : warning LNK4006: subhook_disasm already defined in subhook_x86.obj; second definition ignored
1>subhook.obj : warning LNK4006: subhook_unprotect already defined in subhook_windows.obj; second definition ignored
1>subhook.obj : warning LNK4006: subhook_alloc_code already defined in subhook_windows.obj; second definition ignored
1>subhook.obj : warning LNK4006: subhook_free_code already defined in subhook_windows.obj; second definition ignored

**Comment by Hyjarion** [comment]
Solution: Copy all files into your project folder BUT only press "Include In Project" on subhook.c !

**Comment by HugoMskn** [comment]
Hey I have a similar error, LNK2001	unresolved external symbol  _subhook_disasm_handle
