### ISSUE TITLE
Hook pramm *const this

### ISSUE THREAD

**Issue by hoangdung500** [Zeex/subhook#71]
Hi
I use centos7
I've been trying to hook 1 week into this function.
void __cdecl XPlayerServer::OnHandshakeRequest(XPlayerServer *const this, int a_1, BYTE *b_1, size_t c){
      .................
}
Code of me:
void  XPlayerServer_OnHandshakeRequest(void *xlayserver, int nConnIndex, size_t pbyData, size_t uDataLen)
{
	((ptrXPS_OHSR)subhook_get_trampoline(hook3))(xlayserver,nConnIndex,pbyData,uDataLen);
}

But *xlayserver seems to be wrong.
The system was standing when the hook was hooked up.
Thank you for your help.

**Comment by ba0f3** [comment]
IMO, calling convention of orig function should be __thiscall. And your function should declare like this:

`void __thiscall XPlayerServer_OnHandshakeRequest(void *xlayserver, int nConnIndex, size_t pbyData, size_t uDataLen)`

**Comment by hoangdung500** [comment]
Thank you.
I fix done.
