### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Eltii** [Zeex/subhook#8]
Not a a bug In the program but still an Issues , why ?
without a license the project is all rights reserved for you and we are not allowed to use it or run it .
and please dont select GPL or LGPL :(, use MIT if you want to people to include your copyright in the program or Public Domain If Its Just Something your giving to people without any restrictions ..

**Comment by Zeex** [comment]
The license is a 2-clause BSD license, you can see it in the beginning of individual source files. I forgot to mention it in README though, sorry about that (now fixed).

**Comment by Eltii** [comment]
Oh Sorry Didn't See it Thanks Anyways :D
